spring:
  datasource:
    url: jdbc:mysql://localhost:3306/temp?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: lihuan4714
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml

#showSql
logging:
  level:
    fun:
      muzi:
        repository: debug

server:
  port: 8181

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: countsql
